export const SEED_PROPERTIES = [
  {
    "id": 1,
    "title": "Stanza Living - Kyoto House (Premium Men's PG & Co-living)",
    "description": "High-end luxury men's PG located right next to Sony World Signal, Koramangala. Includes 3-time chef-curated meals, ultra-high-speed WiFi, daily housekeeping, gaming lounge, and biometric security.",
    "category": "pg",
    "gender_preference": "male",
    "address": "80 Feet Road, 4th Block, Koramangala",
    "locality": "Koramangala",
    "city": "Bangalore",
    "state": "Karnataka",
    "pincode": "560034",
    "latitude": 12.9352,
    "longitude": 77.6245,
    "price": 14500.0,
    "deposit": 29000.0,
    "maintenance_charges": 0.0,
    "food_included": true,
    "electricity_charges": "Included",
    "property_size_sqft": 240,
    "bedrooms_or_sharing": "2 Sharing & Single",
    "bathrooms": 1,
    "furnishing": "Furnished",
    "amenities": ["High-Speed WiFi", "3 Meals Daily", "Air Conditioning", "Power Backup", "Washing Machine", "Daily Housekeeping", "CCTV & Biometric Entry", "Gaming Zone", "Geyser"],
    "photos": [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=80"
    ],
    "rules": ["No smoking inside rooms", "Gate closes at 11:30 PM", "Visitors allowed in lounge area"],
    "is_available": true,
    "is_featured": true,
    "rating": 4.8,
    "total_reviews": 42,
    "owner_name": "Ramesh Chandra",
    "owner_phone": "+91 98450 12389",
    "owner_email": "ramesh.pg@perchstay.com"
  },
  {
    "id": 2,
    "title": "Zolo Blossom - Executive Women's PG & Studio",
    "description": "Exclusive and ultra-secure ladies PG located in HSR Layout Sector 2, walking distance from 27th Main. 24/7 female security guard, nutritious North & South Indian food, high-speed WiFi, gym, and automatic power backup.",
    "category": "pg",
    "gender_preference": "female",
    "address": "14th Main Rd, Sector 2, HSR Layout",
    "locality": "HSR Layout",
    "city": "Bangalore",
    "state": "Karnataka",
    "pincode": "560102",
    "latitude": 12.9116,
    "longitude": 77.6389,
    "price": 13000.0,
    "deposit": 26000.0,
    "maintenance_charges": 0.0,
    "food_included": true,
    "electricity_charges": "Included",
    "property_size_sqft": 200,
    "bedrooms_or_sharing": "2 Sharing / 3 Sharing",
    "bathrooms": 1,
    "furnishing": "Furnished",
    "amenities": ["24/7 Security Guard", "3 Meals Daily", "High-Speed WiFi", "Washing Machine", "Geyser", "CCTV", "Refrigerator", "Elevator", "Power Backup"],
    "photos": [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1540518614846-7ede433c4550?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=80"
    ],
    "rules": ["Female guests only", "Curfew 10:30 PM", "No loud music after 11 PM"],
    "is_available": true,
    "is_featured": true,
    "rating": 4.9,
    "total_reviews": 68,
    "owner_name": "Pooja Hegde",
    "owner_phone": "+91 97412 88901",
    "owner_email": "pooja.blossom@perchstay.com"
  },
  {
    "id": 3,
    "title": "Sunstone Luxury 2 BHK Apartment for Rent",
    "description": "Spacious, east-facing 2 BHK flat with modular kitchen, private balcony, covered car parking, swimming pool, gym, and clubhouse in a gated society. Perfect for IT professionals and families.",
    "category": "house",
    "gender_preference": "family",
    "address": "100 Feet Road, HAL 2nd Stage, Indiranagar",
    "locality": "Indiranagar",
    "city": "Bangalore",
    "state": "Karnataka",
    "pincode": "560038",
    "latitude": 12.9784,
    "longitude": 77.6408,
    "price": 38000.0,
    "deposit": 150000.0,
    "maintenance_charges": 3500.0,
    "food_included": false,
    "electricity_charges": "As per meter",
    "property_size_sqft": 1250,
    "bedrooms_or_sharing": "2 BHK",
    "bathrooms": 2,
    "furnishing": "Semi-Furnished",
    "amenities": ["Covered Car Parking", "Swimming Pool", "Clubhouse", "24/7 Security", "Gym", "Power Backup", "Children Play Area", "Intercom", "Balcony"],
    "photos": [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1000&q=80"
    ],
    "rules": ["Families & working professionals preferred", "Small pets allowed", "No subletting"],
    "is_available": true,
    "is_featured": true,
    "rating": 4.7,
    "total_reviews": 19,
    "owner_name": "Vikram Sethi",
    "owner_phone": "+91 99800 44552",
    "owner_email": "vikram.sethi@indiranagarhomes.com"
  },
  {
    "id": 4,
    "title": "Olive Serviced Suites & Boutique Hotel",
    "description": "Modern boutique suites with kitchenette, daily buffet breakfast, plush queen beds, room service, high-speed optic fiber WiFi, and work desk. Available for daily, weekly, and monthly bookings.",
    "category": "hotel",
    "gender_preference": "all",
    "address": "ITPB Main Road, Whitefield",
    "locality": "Whitefield",
    "city": "Bangalore",
    "state": "Karnataka",
    "pincode": "560066",
    "latitude": 12.9860,
    "longitude": 77.7340,
    "price": 2800.0,
    "deposit": 0.0,
    "maintenance_charges": 0.0,
    "food_included": true,
    "electricity_charges": "Included",
    "property_size_sqft": 450,
    "bedrooms_or_sharing": "Studio Suite",
    "bathrooms": 1,
    "furnishing": "Furnished",
    "amenities": ["Complimentary Breakfast", "Work Desk", "Smart TV with Netflix", "Kitchenette", "Room Service", "Daily Housekeeping", "Valet Parking", "Gym"],
    "photos": [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80"
    ],
    "rules": ["Valid Govt ID required at check-in", "Couples friendly", "Non-smoking rooms available"],
    "is_available": true,
    "is_featured": true,
    "rating": 4.9,
    "total_reviews": 115,
    "owner_name": "Ananya Roy",
    "owner_phone": "+91 98860 33119",
    "owner_email": "booking@olivesuites.com"
  },
  {
    "id": 5,
    "title": "Urban Nest - Co-living & Unisex PG for Techies",
    "description": "Vibrant co-living community for male & female professionals working in Electronic City Phase 1. Features high-speed fiber internet, community kitchen, co-working desks, terrace lounge, and weekly cleaning.",
    "category": "pg",
    "gender_preference": "unisex",
    "address": "Neeladri Road, Electronic City Phase 1",
    "locality": "Electronic City",
    "city": "Bangalore",
    "state": "Karnataka",
    "pincode": "560100",
    "latitude": 12.8399,
    "longitude": 77.6770,
    "price": 11500.0,
    "deposit": 23000.0,
    "maintenance_charges": 0.0,
    "food_included": true,
    "electricity_charges": "Included",
    "property_size_sqft": 220,
    "bedrooms_or_sharing": "2 Sharing & Private Rooms",
    "bathrooms": 1,
    "furnishing": "Furnished",
    "amenities": ["High-Speed WiFi", "Co-working Space", "Community Kitchen", "Terrace Garden", "Power Backup", "Washing Machine", "CCTV", "Snooker Table"],
    "photos": [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1502005229762-ee1e39b9c9f0?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1000&q=80"
    ],
    "rules": ["Co-living environment", "No loud music after midnight", "Common spaces to be kept clean"],
    "is_available": true,
    "is_featured": false,
    "rating": 4.6,
    "total_reviews": 31,
    "owner_name": "Siddharth Rao",
    "owner_phone": "+91 91100 22334",
    "owner_email": "siddharth@urbannest.in"
  },
  {
    "id": 6,
    "title": "Greenview 3 BHK Luxury Villa with Private Garden",
    "description": "Independent gated 3 BHK duplex villa in a peaceful layout in Harlur Road. Comes with private terrace garden, modular Italian kitchen, home automation, 2-car covered parking, and 24/7 security guard.",
    "category": "villa",
    "gender_preference": "family",
    "address": "Harlur Main Road, near Sarjapur Road",
    "locality": "Sarjapur Road",
    "city": "Bangalore",
    "state": "Karnataka",
    "pincode": "560103",
    "latitude": 12.8984,
    "longitude": 77.6698,
    "price": 68000.0,
    "deposit": 300000.0,
    "maintenance_charges": 4500.0,
    "food_included": false,
    "electricity_charges": "As per meter",
    "property_size_sqft": 2400,
    "bedrooms_or_sharing": "3 BHK Villa",
    "bathrooms": 3,
    "furnishing": "Furnished",
    "amenities": ["Private Garden", "Covered 2-Car Parking", "Modular Kitchen", "Home Automation", "Solar Water Heater", "Gated Security", "Power Backup", "Pet Friendly"],
    "photos": [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80"
    ],
    "rules": ["Families preferred", "Pet friendly", "Sub-leasing strictly prohibited"],
    "is_available": true,
    "is_featured": true,
    "rating": 4.9,
    "total_reviews": 14,
    "owner_name": "Deepak Balakrishnan",
    "owner_phone": "+91 98455 77881",
    "owner_email": "deepak.villa@gmail.com"
  }
];
